const {test,before,after}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const crypto=require('node:crypto');const {PGlite}=require('@electric-sql/pglite');require('./register.cjs');const {businessDate,addDays,torontoInstant}=require('../lib/businessTime.ts');
let db;const u={admin:crypto.randomUUID(),pt:crypto.randomUUID(),pt2:crypto.randomUUID(),client:crypto.randomUUID(),client2:crypto.randomUUID(),nc:crypto.randomUUID(),manager:crypto.randomUUID(),marketing:crypto.randomUUID()};let c1,c2,p1,p2,booking,purchase,createdClient,finalized;const tomorrow=addDays(businessDate(),1),slot=torontoInstant(tomorrow,600),slot2=torontoInstant(tomorrow,660);const windows=Array.from({length:7},(_,weekday)=>({weekday,start_minute:420,end_minute:1200}));
async function root(){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub','',false)");}
async function actor(id,role='authenticated'){await root();await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec(`set role ${role}`);}
async function scalar(q,p=[]){return (await db.query(q,p)).rows[0]?.v;}
async function rpc(name,args){const keys=Object.keys(args);return scalar(`select public.${name}(${keys.map((k,i)=>`${k} => $${i+1}`).join(',')}) as v`,keys.map(k=>typeof args[k]==='object'&&args[k]!==null?JSON.stringify(args[k]):args[k]));}
async function reserve(who,trainer,start,key=crypto.randomUUID()){await root();const grant=await rpc('fxa_issue_slot_grant',{p_actor:who,p_trainer:trainer,p_start:start});await actor(who);return rpc('fxa_reserve_booking',{p_trainer_id:trainer,p_starts_at:start,p_request_id:key,p_grant_id:grant});}
async function createClient(name='Synthetic Client',paid=500){await actor(u.admin);return rpc('fxa_create_client',{p_request_id:crypto.randomUUID(),p_client:{full_name:name,email:'synthetic@example.test'},p_package:{sessions:12,value:1000,paid,name:'Test package'}});}
before(async()=>{db=new PGlite();await db.exec(fs.readFileSync('tests/base-schema.sql','utf8'));await db.exec(fs.readFileSync('supabase/migrations/20260907202306_core_booking_repair.sql','utf8'));for(const [k,id]of Object.entries(u))await db.query('insert into profiles(id,role,full_name)values($1,$2,$3)',[id,{pt:'trainer',pt2:'trainer',client2:'client',nc:'nutrition_coach',marketing:'marketing_manager'}[k]||k,k]);
 c1=crypto.randomUUID();c2=crypto.randomUUID();p1=crypto.randomUUID();p2=crypto.randomUUID();await db.query("insert into clients(id,profile_id,full_name,qr_token,assigned_trainer_id)values($1,$2,'A','test-a',$3),($4,$5,'B','test-b',$3)",[c1,u.client,u.pt,c2,u.client2]);await db.query("insert into session_packages(id,client_id,total_sessions,remaining_sessions,status)values($1,$2,12,12,'active'),($3,$4,12,12,'active')",[p1,c1,p2,c2]);for(const id of [u.pt,u.pt2]){await actor(id);await rpc('fxa_save_availability',{p_windows:windows});}});after(async()=>{await db.close();});
test('migration and weekly availability persisted',async()=>{await root();assert.equal(await scalar('select count(*)::int as v from trainer_availability'),14);});
test('weekly overlapping windows rollback to previous schedule',async()=>{await actor(u.pt);await assert.rejects(rpc('fxa_save_availability',{p_windows:[{weekday:1,start_minute:420,end_minute:600},{weekday:1,start_minute:480,end_minute:660}]}),/overlap/);assert.equal(await scalar('select count(*)::int as v from trainer_availability'),7);});
test('client cannot edit PT availability',async()=>{await actor(u.client);await assert.rejects(rpc('fxa_save_availability',{p_windows:windows}),/Access denied/);});
let requestId=crypto.randomUUID();test('valid booking saves contacts and reserves without charging',async()=>{booking=await reserve(u.client,u.pt,slot,requestId);await root();const r=(await db.query('select * from bookings where id=$1',[booking.id])).rows[0];assert.equal(r.client_id,c1);assert.equal(r.client_name,'A');assert.equal(r.package_id,p1);assert.equal(await scalar('select remaining_sessions as v from session_packages where id=$1',[p1]),12);});
test('same idempotency key replays same booking',async()=>{const again=await reserve(u.client,u.pt,slot,requestId);assert.equal(again.id,booking.id);await root();assert.equal(await scalar('select count(*)::int as v from bookings'),1);});
test('idempotency key cannot be reused for different slot',async()=>{await assert.rejects(reserve(u.client,u.pt,slot2,requestId),/different input/);});
test('second client cannot book an occupied PT slot',async()=>{await assert.rejects(reserve(u.client2,u.pt,slot),/conflict/);});
test('same client cannot book another PT at same time',async()=>{await assert.rejects(reserve(u.client,u.pt2,slot),/conflict/);});
test('adjacent slot remains available',async()=>{const r=await reserve(u.client2,u.pt,slot2);assert.ok(r.id);});
test('outside published hours is rejected',async()=>{await assert.rejects(reserve(u.client2,u.pt,torontoInstant(tomorrow,360)),/unavailable/);});
test('client cannot mint Google verification grant',async()=>{await actor(u.client);await assert.rejects(rpc('fxa_issue_slot_grant',{p_actor:u.client,p_trainer:u.pt,p_start:slot2}),/permission denied/);});
test('missing grant cannot bypass server Google check',async()=>{await actor(u.client);await assert.rejects(rpc('fxa_reserve_booking',{p_trainer_id:u.pt,p_starts_at:slot2,p_request_id:crypto.randomUUID(),p_grant_id:crypto.randomUUID()}),/verification expired/);});
test('direct insert bypass blocked by database permissions',async()=>{await actor(u.client);await assert.rejects(db.query("insert into bookings(client_id,trainer_id,client_name,starts_at,ends_at)values($1,$2,'forged',$3,$3::timestamptz+interval '1 hour')",[c1,u.pt,slot]),/permission denied/);});
test('client and unrelated PT cannot read other bookings',async()=>{await actor(u.client2);assert.equal(await scalar('select count(*)::int as v from bookings where id=$1',[booking.id]),0);await actor(u.pt2);assert.equal(await scalar('select count(*)::int as v from bookings'),0);});
test('Google refresh tokens not readable by authenticated PT',async()=>{await actor(u.pt);await assert.rejects(db.query('select access_token from trainer_google_calendar_connections'),/permission denied/);});
test('block cannot overwrite confirmed booking',async()=>{await actor(u.pt);await assert.rejects(rpc('fxa_block_time',{p_starts_at:slot,p_ends_at:slot2,p_reason:'test'}),/book/i);});
test('one-time block prevents reservation',async()=>{const start=torontoInstant(tomorrow,720),end=torontoInstant(tomorrow,780);await actor(u.pt);await rpc('fxa_block_time',{p_starts_at:start,p_ends_at:end,p_reason:'Break'});await assert.rejects(reserve(u.client,u.pt,start),/blocked/);});
test('another client cannot cancel a booking',async()=>{await actor(u.client2);await assert.rejects(rpc('fxa_cancel_booking',{p_booking_id:booking.id}),/Access denied/);});
test('staff cancellation requires a reason',async()=>{await actor(u.pt);await assert.rejects(rpc('fxa_cancel_booking',{p_booking_id:booking.id}),/reason/);});
test('8h01m cancellation allowed; 7h59m blocked server-side',async()=>{await root();await db.query("update bookings set starts_at=clock_timestamp()+interval '7 hours 59 minutes',ends_at=clock_timestamp()+interval '8 hours 59 minutes' where id=$1",[booking.id]);await actor(u.client);await assert.rejects(rpc('fxa_cancel_booking',{p_booking_id:booking.id}),/8 hours/);await root();await db.query("update bookings set starts_at=clock_timestamp()+interval '8 hours 1 minute',ends_at=clock_timestamp()+interval '9 hours 1 minute' where id=$1",[booking.id]);await actor(u.client);await rpc('fxa_cancel_booking',{p_booking_id:booking.id});await root();assert.equal(await scalar('select status as v from bookings where id=$1',[booking.id]),'cancelled');});
test('sync lease prevents simultaneous workers and stale completion',async()=>{await root();const claim=await rpc('fxa_claim_booking_sync',{p_booking_id:booking.id});assert.ok(claim.lease);assert.equal(await rpc('fxa_claim_booking_sync',{p_booking_id:booking.id}),null);await db.query('update bookings set sync_version=sync_version+1 where id=$1',[booking.id]);await rpc('fxa_finish_booking_sync',{p_booking_id:booking.id,p_lease:claim.lease,p_version:claim.sync_version,p_event_id:'fa-test',p_error:null});assert.equal(await scalar('select google_sync_status as v from bookings where id=$1',[booking.id]),'pending');});
test('preview scan never deducts a session',async()=>{await actor(u.pt);const r=await rpc('fxa_preview_session',{p_qr_token:'test-a'});assert.equal(r.remaining_after,12);});
const scanKey=crypto.randomUUID();const scanArgs={p_request_id:scanKey,p_qr_token:'test-a',p_session_type:'training',p_session_status:'success',p_topic:'Strength',p_content:'Squat 3x8',p_note:'Good form'};
test('empty session content fails before deduction',async()=>{await actor(u.pt);await assert.rejects(rpc('fxa_finalize_session',{...scanArgs,p_content:''}),/Topic and Content/);await root();assert.equal(await scalar('select remaining_sessions as v from session_packages where id=$1',[p1]),12);});
test('finalize commits note and deduction together',async()=>{await actor(u.pt);finalized=await rpc('fxa_finalize_session',scanArgs);assert.equal(finalized.remaining_after,11);await root();const h=(await db.query('select * from session_history where id=$1',[finalized.history_id])).rows[0];assert.equal(h.session_content,'Squat 3x8');assert.equal(h.trainer_note,'Good form');});
test('retry Save and Finish does not charge again',async()=>{await actor(u.pt);assert.equal((await rpc('fxa_finalize_session',scanArgs)).history_id,finalized.history_id);await root();assert.equal(await scalar('select remaining_sessions as v from session_packages where id=$1',[p1]),11);});
test('note write failure rolls back charge and history',async()=>{await root();await db.exec("create function test_fail_note() returns trigger language plpgsql as $$begin if new.session_topic='FORCE_FAILURE' then raise exception 'Injected note failure';end if;return new;end$$;create trigger test_note before update on session_history for each row execute function test_fail_note();");await actor(u.pt);await assert.rejects(rpc('fxa_finalize_session',{...scanArgs,p_request_id:crypto.randomUUID(),p_qr_token:'test-b',p_topic:'FORCE_FAILURE'}),/Injected/);await root();assert.equal(await scalar('select remaining_sessions as v from session_packages where id=$1',[p2]),12);assert.equal(await scalar('select count(*)::int as v from session_history where client_id=$1',[c2]),0);await db.exec('drop trigger test_note on session_history;drop function test_fail_note();');});
test('old charge-first RPC no longer executable by PT',async()=>{await actor(u.pt);await assert.rejects(rpc('record_staff_session',{p_qr_token:'test-b'}),/permission denied/);});
test('paid and debt amounts persist with matching initial income',async()=>{createdClient=await createClient();await root();const cp=(await db.query('select * from client_purchases where client_id=$1',[createdClient])).rows[0];purchase=cp.id;assert.equal(cp.status,'partial');assert.equal(Number(cp.balance_due),500);assert.equal(Number(await scalar('select sum(amount) as v from business_transactions where client_id=$1',[createdClient])),500);});
test('client creation failure does not leave orphan client or package',async()=>{await root();const before=await scalar('select count(*)::int as v from clients');await db.exec("create function test_fail_income() returns trigger language plpgsql as $$begin raise exception 'Injected ledger failure';end$$;create trigger test_income before insert on business_transactions for each row execute function test_fail_income();");await assert.rejects(createClient('Rollback'),/Injected ledger/);await root();assert.equal(await scalar('select count(*)::int as v from clients'),before);await db.exec('drop trigger test_income on business_transactions;drop function test_fail_income();');});
test('renewal updates credits, payment state and income atomically',async()=>{await actor(u.admin);await rpc('fxa_renew_package',{p_request_id:crypto.randomUUID(),p_client_id:createdClient,p_package:{sessions:6,value:600,paid:300,name:'Renew'}});await root();assert.equal(await scalar('select remaining_sessions as v from session_packages where client_id=$1',[createdClient]),18);assert.equal(Number(await scalar('select sum(amount) as v from business_transactions where client_id=$1',[createdClient])),800);});
test('debt payment retry adds income only once',async()=>{await actor(u.admin);const a={p_request_id:crypto.randomUUID(),p_purchase_id:purchase,p_amount:100,p_date:businessDate()};await rpc('fxa_record_debt_payment',a);await rpc('fxa_record_debt_payment',a);await root();assert.equal(Number(await scalar('select balance_due as v from client_purchases where id=$1',[purchase])),400);assert.equal(Number(await scalar('select sum(amount) as v from business_transactions where purchase_id=$1',[purchase])),600);});
test('overpayment rejected without changing debt',async()=>{await actor(u.admin);await assert.rejects(rpc('fxa_record_debt_payment',{p_request_id:crypto.randomUUID(),p_purchase_id:purchase,p_amount:401,p_date:businessDate()}),/Invalid payment/);});
test('no-show to success remains chargeable (no incorrect refund)',async()=>{await root();await db.query("update session_history set status='no_show' where id=$1",[finalized.history_id]);await actor(u.admin);await rpc('fxa_edit_session_history',{p_history_id:finalized.history_id,p_client_id:c1,p_trainer_id:u.pt,p_status:'success',p_created_at:new Date().toISOString(),p_message:'Fixed status',p_note:'Good'});await root();assert.equal(await scalar('select remaining_sessions as v from session_packages where id=$1',[p1]),11);});
test('finance balance includes over 1000 ledger entries',async()=>{await root();const id=crypto.randomUUID();await db.query('insert into finance_accounts(id,name,opening_balance)values($1,$2,100)',[id,'Test account']);await db.query("insert into business_transactions(transaction_type,title,amount,account_id)select 'income','Synthetic',1,$1 from generate_series(1,1251)",[id]);await actor(u.admin);const r=await db.query('select * from fxa_finance_balances()');assert.equal(Number(r.rows.find(x=>x.id===id).balance),1351);});
test('null schedule cannot silently clear availability',async()=>{await actor(u.pt);await assert.rejects(rpc('fxa_save_availability',{p_windows:null}),/Invalid weekly/);});
test('staff cannot bypass session transaction with direct package update',async()=>{await actor(u.pt);const r=await db.query('update session_packages set remaining_sessions=999 where id=$1 returning id',[p1]);assert.equal(r.rows.length,0);});
test('staff cannot directly change client identity or assignment',async()=>{await actor(u.pt);await assert.rejects(db.query("update clients set full_name='FORGED' where id=$1",[c1]),/only update client notes/);});
test('Marketing Manager can add an unconverted lead',async()=>{await actor(u.marketing);const r=await db.query("insert into leads(full_name,status)values('Synthetic lead','new')returning id");assert.ok(r.rows[0].id);});
test('Marketing Manager cannot create a converted lead',async()=>{await actor(u.marketing);await assert.rejects(db.query("insert into leads(full_name,status)values('Forged conversion','converted')"),/row-level security/);});
