// Isolated integration harness. Never deploy this test-only HTTP server.
const http=require('node:http'),fs=require('node:fs'),crypto=require('node:crypto');const {PGlite}=require('@electric-sql/pglite');
const id=()=>crypto.randomUUID();const users={admin:{id:id(),role:'admin',full_name:'Test Admin'},pt:{id:id(),role:'trainer',full_name:'Tian Test'},pt2:{id:id(),role:'trainer',full_name:'Other PT'},client:{id:id(),role:'client',full_name:'Test Client'},nc:{id:id(),role:'nutrition_coach',full_name:'Test NC'},manager:{id:id(),role:'manager',full_name:'Test Manager'}};
const clientId=id(),packageId=id(),qr=id();const events=new Map();const db=new PGlite();const port=Number(process.env.FXA_FIXTURE_PORT||54321);
function token(user){return Buffer.from(JSON.stringify({alg:'HS256',typ:'JWT'})).toString('base64url')+'.'+Buffer.from(JSON.stringify({sub:user.id,exp:Math.floor(Date.now()/1000)+3600,aud:'authenticated',role:'authenticated'})).toString('base64url')+'.synthetic';}
function session(u){const user={...u,email:u.role+'@example.test',aud:'authenticated',created_at:new Date().toISOString(),app_metadata:{},user_metadata:{}};return{access_token:token(u),token_type:'bearer',refresh_token:'synthetic-refresh',expires_in:3600,expires_at:Math.floor(Date.now()/1000)+3600,user};}
const ident=s=>{if(!/^[a-z_][a-z0-9_]*$/i.test(s))throw Error('Invalid identifier');return '"'+s+'"';};
function filters(url,params){const clauses=[];for(const [key,val] of url.searchParams){if(['select','order','limit','offset'].includes(key))continue;if(key==='or'){const parts=val.replace(/^\(|\)$/g,'').split(',');clauses.push('('+parts.map(p=>{const [k,op,...vs]=p.split('.');return condition(k,op+'.'+vs.join('.'),params);}).join(' or ')+')');}else clauses.push(condition(key,val,params));}return clauses.length?' where '+clauses.join(' and '):'';}
function condition(key,value,params){const [op,...rest]=value.split('.'),v=rest.join('.'),column=ident(key);if(op==='is')return column+(v==='null'?' is null':v==='true'?' is true':' is false');if(op==='not'&&v==='is.null')return column+' is not null';if(op==='in'){const values=v.replace(/^\(|\)$/g,'').split(',').filter(Boolean);if(!values.length)return'false';return column+' in ('+values.map(x=>{params.push(x.replace(/^"|"$/g,''));return'$'+params.length}).join(',')+')';}const oper={eq:'=',neq:'<>',gt:'>',gte:'>=',lt:'<',lte:'<=',ilike:'ilike'}[op];if(!oper)throw Error('Unsupported fixture filter '+op);params.push(v);return column+oper+'$'+params.length;}
async function main(){await db.exec(fs.readFileSync('tests/base-schema.sql','utf8'));await db.exec(fs.readFileSync('supabase/migrations/20260907202306_core_booking_repair.sql','utf8'));for(const u of Object.values(users))await db.query('insert into profiles(id,role,full_name,email)values($1,$2,$3,$4)',[u.id,u.role,u.full_name,u.role+'@example.test']);await db.query("insert into clients(id,profile_id,full_name,email,qr_token,assigned_trainer_id) values($1,$2,'Test Client','client@example.test',$3,$4)",[clientId,users.client.id,qr,users.pt.id]);await db.query("insert into session_packages(id,client_id,total_sessions,remaining_sessions,used_sessions,status)values($1,$2,12,12,0,'active')",[packageId,clientId]);for(const u of [users.pt,users.pt2]){await db.query("insert into trainer_google_calendar_connections(trainer_id,google_email,access_token,refresh_token,token_expiry)values($1,'trainer@example.test','synthetic','synthetic',now()+interval '1 day')",[u.id]);for(let weekday=0;weekday<7;weekday++)await db.query('insert into trainer_availability(trainer_id,weekday,start_minute,end_minute)values($1,$2,420,1200)',[u.id,weekday]);}
const info={users:Object.fromEntries(Object.entries(users).map(([k,u])=>[k,session(u)])),clientId,packageId,qr};fs.writeFileSync(process.env.FXA_FIXTURE_INFO||'/tmp/fxa-fixture.json',JSON.stringify(info));
const server=http.createServer(async(req,res)=>{res.setHeader('Access-Control-Allow-Origin','http://localhost:3000');res.setHeader('Access-Control-Allow-Headers','authorization,apikey,content-type,x-client-info,prefer,range,accept,range-unit,x-supabase-api-version');res.setHeader('Access-Control-Allow-Methods','GET,HEAD,POST,PATCH,DELETE,OPTIONS');res.setHeader('Access-Control-Expose-Headers','content-range');if(req.method==='OPTIONS'){res.writeHead(204);return res.end();}
const send=(x,status=200)=>{res.statusCode=status;res.setHeader('Content-Type','application/json');res.end(JSON.stringify(x));};try{const url=new URL(req.url,'http://localhost');let body='';for await(const c of req){body+=c;if(body.length>64000)throw Error('Too large');}const data=body?JSON.parse(body):{};const bearer=(req.headers.authorization||'').replace(/^Bearer /,'');const isService=bearer==='local-test-service-role-key';let actor;try{const claims=JSON.parse(Buffer.from(bearer.split('.')[1],'base64url'));actor=Object.values(users).find(u=>u.id===claims.sub);}catch{}
if(url.pathname.startsWith('/auth/v1/user'))return actor?send(session(actor).user):send({message:'Invalid fixture token'},401);
if(url.pathname.startsWith('/_google/')){if(url.pathname.endsWith('freeBusy'))return send({calendars:{primary:{busy:[]}}});if(url.pathname.endsWith('/events')&&req.method==='POST'){if(events.has(data.id))return send({},409);events.set(data.id,data);return send(data);}const key=url.pathname.split('/').pop();if(req.method==='DELETE'){events.delete(key);return send({});}return events.has(key)?send(events.get(key)):send({},404);}
if(!actor&&!isService)return send({message:'Authentication required'},401);
const output=await db.transaction(async tx=>{await tx.query("select set_config('request.jwt.claim.sub',$1,true)",[actor?.id||'']);await tx.exec('set local role '+(isService?'service_role':'authenticated'));
if(url.pathname.startsWith('/rest/v1/rpc/')){const name=url.pathname.split('/').pop();const keys=Object.keys(data);const q=`select public.${ident(name)}(${keys.map((k,i)=>ident(k)+' => $'+(i+1)).join(',')}) as value`;const result=await tx.query(q,keys.map(k=>typeof data[k]==='object'&&data[k]!==null?JSON.stringify(data[k]):data[k]));return {value:result.rows[0]?.value??null};}
const table=url.pathname.split('/').pop();const exists=await tx.query("select 1 from information_schema.tables where table_schema='public' and table_name=$1",[table]);if(!exists.rows.length)return{rows:[],count:0};let params=[],q;const single=(req.headers.accept||'').includes('vnd.pgrst.object');if(req.method==='GET'||req.method==='HEAD'){q='select * from public.'+ident(table)+filters(url,params);const count=(await tx.query(q,params)).rows.length;const order=url.searchParams.get('order');if(order)q+=' order by '+order.split(',').map(s=>{const [k,d]=s.split('.');return ident(k)+(d==='desc'?' desc':' asc')}).join(',');if(url.searchParams.has('limit')){params.push(Number(url.searchParams.get('limit')));q+=' limit $'+params.length;}if(url.searchParams.has('offset')){params.push(Number(url.searchParams.get('offset')));q+=' offset $'+params.length;}const r=await tx.query(q,params);return{rows:r.rows,count,single};}
if(req.method==='PATCH'){const keys=Object.keys(data);params=keys.map(k=>data[k]);q='update public.'+ident(table)+' set '+keys.map((k,i)=>ident(k)+'=$'+(i+1)).join(',')+filters(url,params)+' returning *';}
else if(req.method==='POST'){const keys=Object.keys(data);params=keys.map(k=>data[k]);q='insert into public.'+ident(table)+'('+keys.map(ident).join(',')+') values('+keys.map((k,i)=>'$'+(i+1)).join(',')+') returning *';}
else if(req.method==='DELETE'){q='delete from public.'+ident(table)+filters(url,params)+' returning *';}else throw Error('Unsupported method');const result=await tx.query(q,params);return{rows:result.rows,count:result.rows.length,single};});if('value'in output)return send(output.value);if(req.method==='HEAD'){res.setHeader('Content-Range','0-0/'+output.count);res.writeHead(200);return res.end();}if(output.single&&output.rows.length!==1)return send({code:'PGRST116',message:'Expected one row'},406);return send(output.single?output.rows[0]:output.rows);
}catch(e){return send({message:e.message,code:e.code||'FIXTURE_ERROR'},400);}});server.listen(port,'127.0.0.1',()=>console.log('ISOLATED_FIXTURE_READY '+port));process.on('SIGTERM',async()=>{server.close();await db.close();process.exit(0);});}
main().catch(e=>{console.error(e);process.exit(1)});
