require('./register.cjs');const {test,after}=require('node:test');const assert=require('node:assert/strict');const crypto=require('node:crypto');const baseFetch=global.fetch;
const connection={id:'conn',trainer_id:'pt',access_token:'synthetic',refresh_token:'old-refresh',token_expiry:new Date(Date.now()+3600000).toISOString(),calendar_id:'primary'};
let current={...connection},booking=null,finish=null,updated=null;
function query(table){const q={select(){return q},eq(){return q},update(data){updated=data;return q},maybeSingle:async()=>({data:table==='bookings'?{sync_version:booking?.sync_version,google_sync_status:'synced'}:current,error:null}),then(ok,no){return Promise.resolve({error:null,data:current}).then(ok,no)}};return q;}
const db={from:query,async rpc(name,args){if(name==='fxa_claim_booking_sync')return{data:booking,error:null};finish=args;return{error:null};}};
const p=require.resolve('../lib/supabaseServer.ts');require.cache[p]={id:p,filename:p,loaded:true,exports:{createServiceSupabaseClient:()=>db}};
const g=require('../lib/googleCalendar.ts'),sync=require('../lib/booking/sync.ts');after(()=>{global.fetch=baseFetch;});
const response=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json'}});
test('Google HTTP 403 does not open false availability',async()=>{global.fetch=async()=>response({error:{}},403);await assert.rejects(g.getBusyTimes('pt','2026-09-08','2026-09-09'),/Cannot verify/);});
test('Google per-calendar errors fail closed even with HTTP 200',async()=>{global.fetch=async()=>response({calendars:{primary:{busy:[],errors:[{reason:'notFound'}]}}});await assert.rejects(g.getBusyTimes('pt','2026-09-08','2026-09-09'),/Cannot verify/);});
test('Google malformed busy intervals rejected',async()=>{global.fetch=async()=>response({calendars:{primary:{busy:[{start:'bad',end:'bad'}]}}});await assert.rejects(g.getBusyTimes('pt','2026-09-08','2026-09-09'),/Invalid calendar/);});
test('Google disconnected calendar blocks booking',async()=>{current=null;await assert.rejects(g.getBusyTimes('pt','2026-09-08','2026-09-09'),/not connected/);current={...connection};});
test('token refresh preserves prior refresh token when Google omits it',async()=>{process.env.GOOGLE_CLIENT_ID='synthetic';process.env.GOOGLE_CLIENT_SECRET='synthetic';global.fetch=async()=>response({access_token:'new-access',expires_in:3600});await g.refreshGoogleAccessToken({...connection,token_expiry:'2000-01-01'});assert.equal(updated.refresh_token,'old-refresh');});
test('deterministic calendar ID is valid Google base32hex',()=>{const id=crypto.randomUUID();assert.match(sync.googleEventId(id),/^[0-9a-v]{5,1024}$/);assert.equal(sync.googleEventId(id),sync.googleEventId(id));});
function book(){return{id:crypto.randomUUID(),trainer_id:'pt',client_name:'Synthetic',client_email:'test@example.test',starts_at:'2026-09-08T14:00:00Z',ends_at:'2026-09-08T15:00:00Z',status:'booked',sync_version:1,lease:crypto.randomUUID()};}
test('Google outage records retryable error without losing booking',async()=>{booking=book();global.fetch=async()=>response({},503);await sync.syncBooking(booking.id);assert.equal(finish.p_error,'Calendar invitation pending.');assert.equal(finish.p_booking_id,booking.id);});
test('retry event collision verifies same booking instead of creating duplicate',async()=>{booking=book();let n=0;global.fetch=async()=>++n===1?response({},409):response({id:sync.googleEventId(booking.id),extendedProperties:{private:{fxaBookingId:booking.id}}});await sync.syncBooking(booking.id);assert.equal(n,2);assert.equal(finish.p_error,null);});
test('calendar cancellation treats already deleted as success',async()=>{booking={...book(),status:'cancelled'};global.fetch=async()=>response({},410);await sync.syncBooking(booking.id);assert.equal(finish.p_error,null);});
test('legacy linked Google event is verified without duplicate insertion',async()=>{booking={...book(),google_event_id:'legacyid'};let method;global.fetch=async(url,init)=>{method=init.method||'GET';return response({status:'confirmed',start:{dateTime:booking.starts_at},end:{dateTime:booking.ends_at}});};await sync.syncBooking(booking.id);assert.equal(method,'GET');assert.equal(finish.p_error,null);});
