'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { bookingFetch } from '@/lib/booking/client';
import { addDays, businessDate, BUSINESS_TIME_ZONE } from '@/lib/businessTime';
import { canClientCancel, type Interval } from '@/lib/booking/time';
type Staff={id:string;full_name:string;is_main:boolean};
type Booking={id:string;trainer_name:string;starts_at:string;ends_at:string;status:string;google_sync_status:string;can_cancel:boolean};
const label=(value:string)=>new Date(value).toLocaleString('en-CA',{timeZone:BUSINESS_TIME_ZONE,weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});
const time=(value:string)=>new Date(value).toLocaleTimeString('en-CA',{timeZone:BUSINESS_TIME_ZONE,hour:'numeric',minute:'2-digit'});
export default function BookingPanel({adminMode=false}:{adminMode?:boolean}){
 const [clients,setClients]=useState<{id:string;full_name:string}[]>([]),[clientId,setClientId]=useState('');
 const [staff,setStaff]=useState<Staff[]>([]),[trainer,setTrainer]=useState(''),[date,setDate]=useState(businessDate()),[slots,setSlots]=useState<Interval[]>([]),[selected,setSelected]=useState(''),[bookings,setBookings]=useState<Booking[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[refresh,setRefresh]=useState(0),[now,setNow]=useState(()=>Date.now()),[offset,setOffset]=useState(0);
 const operation=useRef(false),requestId=useRef('');
 const loadBookings=useCallback(async()=>{if(adminMode&&!clientId){setBookings([]);return;}const r=await bookingFetch<{bookings:Booking[];serverTime:string}>(`/api/bookings/upcoming${adminMode?`?clientId=${clientId}`:''}`);setBookings(r.bookings);setOffset(Date.parse(r.serverTime)-Date.now());},[adminMode,clientId]);
 useEffect(()=>{let alive=true; if(adminMode)bookingFetch<{clients:{id:string;full_name:string}[]}>('/api/bookings/clients').then(r=>{if(alive){setClients(r.clients);setClientId(r.clients[0]?.id||'');}}).catch(e=>setMessage(e.message)); const t=setInterval(()=>setNow(Date.now()),30000);return()=>{alive=false;clearInterval(t);};},[adminMode]);
 useEffect(()=>{if(adminMode&&!clientId)return;let alive=true;
 bookingFetch<{staff:Staff[]}>(`/api/bookings/staff${adminMode?`?clientId=${clientId}`:''}`).then(r=>{if(alive){setStaff(r.staff);setTrainer(r.staff[0]?.id||'');}}).catch(e=>{if(alive){setMessage(e.message);setLoading(false);}});void Promise.resolve().then(loadBookings).catch(e=>{if(alive)setMessage(e.message);});return()=>{alive=false;};},[adminMode,clientId,loadBookings]);
 useEffect(()=>{if(!trainer||(adminMode&&!clientId))return;let alive=true;requestId.current='';
 Promise.resolve().then(()=>{if(alive){setLoading(true);setSlots([]);setSelected('');}});
 bookingFetch<{slots:Interval[]}>(`/api/bookings/availability?trainerId=${encodeURIComponent(trainer)}&date=${date}${adminMode?`&clientId=${clientId}`:''}`).then(r=>{if(alive)setSlots(r.slots);}).catch(e=>{if(alive)setMessage(e.message);}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[trainer,date,refresh,adminMode,clientId]);
 async function confirm(){if(operation.current||!selected)return;operation.current=true;setSaving(true);setMessage('');requestId.current ||= crypto.randomUUID();
 try{const r=await bookingFetch<{booking:Booking}>('/api/bookings/create','POST',{trainerId:trainer,startsAt:selected,requestId:requestId.current,...(adminMode?{clientId}:{})});setMessage(r.booking.status==='booked'?'Booking confirmed. Your calendar invitation may take a moment to sync.':'This request was already cancelled. Please choose a slot again.');setSelected('');requestId.current='';setRefresh(v=>v+1);await loadBookings();}
 catch(e){setMessage(e instanceof Error?e.message:'Booking failed. Retry using the same selection.');}
 finally{operation.current=false;setSaving(false);}}
 async function cancel(b:Booking){if(operation.current||!window.confirm(`Cancel your session on ${label(b.starts_at)}?`))return;operation.current=true;setSaving(true);
 try{const reason=adminMode?window.prompt('Reason for cancellation')||'':'';if(adminMode&&!reason)return;await bookingFetch('/api/bookings/cancel','POST',{bookingId:b.id,reason});setMessage('Booking cancelled.');await loadBookings();setRefresh(v=>v+1);}catch(e){setMessage(e instanceof Error?e.message:'Cancellation failed.');}finally{operation.current=false;setSaving(false);}}
 return <main className="min-h-screen bg-black px-4 py-8 text-white"><div className="mx-auto max-w-3xl">
  <p className="text-xs font-bold uppercase tracking-[0.35em] text-yellow-400">FXA FITNESS</p><h1 className="mt-4 text-3xl font-black">Book Session</h1><p className="mt-2 text-sm text-gray-400">Choose your trainer, date and time. All times are Toronto time.</p>
  <Link href={adminMode?"/admin":"/client"} className="mt-4 inline-block text-sm font-bold text-yellow-400">{adminMode?"Back to Admin":"Back to Client Portal"}</Link>
  {message&&<p role="status" className="mt-5 rounded-2xl border border-yellow-400/30 bg-yellow-400/10 p-4 text-sm">{message}</p>}
  <section className="mt-6 rounded-[2rem] border border-yellow-400/30 bg-white/[0.06] p-6">
   {adminMode&&<label className="mb-5 block text-sm font-bold">Client<select aria-label="Client" value={clientId} disabled={saving} onChange={e=>{setClientId(e.target.value);setSelected('');setSlots([]);setMessage('');}} className="mt-2 w-full rounded-xl bg-white p-3 text-black">{clients.map(c=><option key={c.id} value={c.id}>{c.full_name}</option>)}</select></label>}
   <label className="block text-sm font-bold">Personal Trainer<select aria-label="Personal Trainer" value={trainer} disabled={saving} onChange={e=>{setTrainer(e.target.value);setSelected('');setSlots([]);setLoading(true);requestId.current='';setMessage('');}} className="mt-2 w-full rounded-xl bg-white p-3 text-black">{staff.map(s=><option key={s.id} value={s.id}>{s.full_name}{s.is_main?' - MAIN PT':''}</option>)}</select></label>
   <label className="mt-5 block text-sm font-bold">Date<input aria-label="Booking date" type="date" value={date} min={businessDate()} max={addDays(businessDate(),13)} disabled={saving} onChange={e=>{setDate(e.target.value);setSelected('');setSlots([]);setLoading(true);requestId.current='';setMessage('');}} className="mt-2 w-full rounded-xl border border-white/20 bg-black p-3 text-white"/></label>
   <h2 className="mt-6 font-bold">Available Times</h2><div className="mt-3 grid grid-cols-3 gap-2 sm:grid-cols-4">{slots.map(s=><button type="button" key={s.starts_at} disabled={saving} aria-pressed={selected===s.starts_at} onClick={()=>{setSelected(s.starts_at);requestId.current='';}} className={`rounded-xl border p-3 text-sm font-bold disabled:opacity-50 ${selected===s.starts_at?'border-yellow-400 bg-yellow-400 text-black':'border-white/20 text-yellow-300'}`}>{time(s.starts_at)}</button>)}</div>
   {loading?<p role="status" className="mt-3 text-gray-400">Checking availability...</p>:!slots.length?<p className="mt-3 text-gray-400">No available slots. Choose another date or trainer.</p>:null}
   {selected&&<div className="mt-6 rounded-2xl border border-white/10 p-4"><h2 className="font-bold text-yellow-400">Booking Summary</h2><p className="mt-2">{staff.find(s=>s.id===trainer)?.full_name}</p><p>{label(selected)} - {time(new Date(Date.parse(selected)+3600000).toISOString())}</p><p className="mt-2 text-xs text-gray-400">Cancellation is available until 8 hours before your session.</p><button type="button" onClick={confirm} disabled={saving} className="mt-4 w-full rounded-2xl bg-yellow-400 px-5 py-3 font-black text-black disabled:opacity-50">{saving?'Saving...':'Confirm Booking'}</button></div>}
  </section>
  <section className="mt-6 rounded-[2rem] border border-white/15 bg-white/[0.06] p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-black">My Bookings</h2><button type="button" disabled={saving} onClick={()=>{void Promise.resolve().then(loadBookings).catch(e=>setMessage(e.message));}} className="text-sm text-yellow-400">Refresh</button></div>
   {!bookings.length&&<p className="mt-4 text-gray-400">No upcoming bookings.</p>}{bookings.map(b=><article key={b.id} className="mt-4 rounded-2xl border border-white/10 p-4"><p className="font-bold text-yellow-300">{label(b.starts_at)}</p><p className="mt-1">{b.trainer_name}</p><p className="mt-1 text-xs text-gray-400">{b.google_sync_status==='synced'?'Calendar synced':'Calendar sync pending; your FXA booking is saved.'}</p>{b.can_cancel&&(adminMode?Date.parse(b.starts_at)>now+offset:canClientCancel(b.starts_at,now+offset))?<button type="button" disabled={saving} onClick={()=>cancel(b)} className="mt-3 rounded-xl border border-white/20 px-4 py-2 text-sm">Cancel Session</button>:<p className="mt-3 text-xs text-gray-500">Cancellation unavailable. Contact FXA Fitness.</p>}</article>)}
  </section>
 </div></main>;
}
